# Generated by Django 2.2.3 on 2019-10-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191022_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
